"""
Micro-Pascal-Compiler/codegen.py
==========================
X86-64 NASM code generator for subset-Pascal.

Calling convention: System V AMD64 ABI (Linux)
-----------------------------------------------
* Integer arguments:  rdi, rsi, rdx, rcx, r8, r9
* Return value:       rax
* Caller-saved:       rax, rcx, rdx, rsi, rdi, r8, r9, r10, r11
* Callee-saved:       rbx, rbp, r12–r15

Stack frame layout
------------------
  [rbp]       = saved old rbp
  [rbp - 8]   = var_1  (first variable declared)
  [rbp - 16]  = var_2
  …
  All variables are 8 bytes (QWORD), Integer/Boolean/Char all fit in rax.

I/O strategy
------------
* write/writeln: uses printf (via PLT) for integers and strings.
  Chars are printed with putchar.
* readln/read:   uses scanf (via PLT).

Boolean representation: 0 = false, 1 = true (stored as QWORD).
Char  representation: zero-extended ASCII byte stored as QWORD.

Label naming: .L<counter>  (local labels, NASM convention).
"""

from __future__ import annotations
from typing import TextIO
import io

from ast_nodes import (
    ASTNode, PascalType, BinOp, UnOp,
    Program, Block, Assignment, IfStatement, WhileStatement, ForStatement,
    WritelnStatement, WriteStatement, ReadlnStatement, ReadStatement,
    BinaryOp, UnaryOp, VarRef,
    IntLiteral, BoolLiteral, CharLiteral, StringLiteral,
    VarDecl,
)


class CodeGenError(Exception):
    pass


class CodeGenerator:
    """
    Traverse an annotated AST and emit NASM x86-64 assembly.

    Usage
    -----
    asm = CodeGenerator(ast).generate()
    print(asm)
    """

    def __init__(self, program: Program):
        self._prog       = program
        self._buf        = io.StringIO()
        self._label_cnt  = 0
        # String literals collected during traversal → emitted in .data section
        self._str_literals: list[tuple[str, str]] = []   # [(label, value), …]

    # ── helpers ───────────────────────────────────────────────

    def _emit(self, line: str = '') -> None:
        self._buf.write(line + '\n')

    def _ins(self, mnemonic: str, *args: str) -> None:
        """Emit a single indented instruction."""
        operands = ', '.join(args)
        self._emit(f'    {mnemonic:<8} {operands}' if operands else f'    {mnemonic}')

    def _label(self, name: str) -> None:
        self._emit(f'{name}:')

    def _new_label(self) -> str:
        self._label_cnt += 1
        return f'.L{self._label_cnt}'

    def _var_addr(self, decl: VarDecl) -> str:
        """rbp-relative address string for a variable."""
        return f'QWORD [rbp - {decl.offset}]'

    def _new_str_label(self, value: str) -> str:
        """Intern a string literal; return its data-section label."""
        lbl = f'_str{len(self._str_literals)}'
        self._str_literals.append((lbl, value))
        return lbl

    # ══════════════════════════════════════════════════════════
    #  Entry point
    # ══════════════════════════════════════════════════════════

    def generate(self) -> str:
        self._emit_header()
        self._emit_data_init()
        self._emit_text_section()
        self._emit_data_section()
        return self._buf.getvalue()

    # ── sections ──────────────────────────────────────────────

    def _emit_header(self) -> None:
        self._emit('; Generated by PascalCompiler — NASM x86-64 (Linux SysV ABI)')
        self._emit(f'; Program: {self._prog.name}')
        self._emit()
        self._emit('global  main')
        self._emit('extern  printf, scanf, putchar, getchar, exit')
        self._emit()

    def _emit_data_init(self) -> None:
        """
        Pre-declare format strings that we know we'll need.
        Dynamic string literals are added later.
        """
        # We'll build the .data section after code-gen (so all string literals
        # are collected).  _emit_data_section() handles this.
        pass

    def _emit_text_section(self) -> None:
        self._emit('section .text')
        self._emit()
        # ── main prologue ──
        self._label('main')
        self._ins('push',  'rbp')
        self._ins('mov',   'rbp', 'rsp')
        # Align stack to 16-byte boundary and reserve space for all locals
        frame_size = self._prog.var_decls[-1].offset if self._prog.var_decls else 0
        # Round up to next multiple of 16
        frame_size = (frame_size + 15) & ~15
        if frame_size:
            self._ins('sub',   'rsp', str(frame_size))
        self._emit()

        # ── body ──
        self._gen_block(self._prog.body)
        self._emit()

        # ── main epilogue ──
        self._ins('xor',   'eax', 'eax')   # return 0
        self._ins('leave')
        self._ins('ret')
        self._emit()

    def _emit_data_section(self) -> None:
        self._emit()
        self._emit('section .data')
        # Fixed format strings
        self._emit('_fmt_int    db  "%lld", 0')
        self._emit('_fmt_intln  db  "%lld", 10, 0')
        self._emit('_fmt_str    db  "%s", 0')
        self._emit('_fmt_strln  db  "%s", 10, 0')
        self._emit('_fmt_char   db  "%c", 0')
        self._emit('_fmt_charln db  "%c", 10, 0')
        self._emit('_fmt_bool   db  "%s", 0')
        self._emit('_fmt_booln  db  "%s", 10, 0')
        self._emit('_str_true   db  "TRUE", 0')
        self._emit('_str_false  db  "FALSE", 0')
        self._emit('_fmt_rdi    db  "%lld", 0')
        self._emit('_fmt_rdc    db  " %c", 0')
        # Collected string literals
        for lbl, val in self._str_literals:
            escaped = val.replace('\\', '\\\\').replace('"', '\\"')
            self._emit(f'{lbl:<12} db  "{escaped}", 0')
        self._emit()

    # ══════════════════════════════════════════════════════════
    #  Statement generators
    # ══════════════════════════════════════════════════════════

    def _gen_block(self, node: Block) -> None:
        for stmt in node.statements:
            self._gen_stmt(stmt)

    def _gen_stmt(self, node: ASTNode) -> None:
        if isinstance(node, Block):
            self._gen_block(node)
        elif isinstance(node, Assignment):
            self._gen_assignment(node)
        elif isinstance(node, IfStatement):
            self._gen_if(node)
        elif isinstance(node, WhileStatement):
            self._gen_while(node)
        elif isinstance(node, ForStatement):
            self._gen_for(node)
        elif isinstance(node, WritelnStatement):
            self._gen_write(node.args, newline=True)
        elif isinstance(node, WriteStatement):
            self._gen_write(node.args, newline=False)
        elif isinstance(node, ReadlnStatement):
            self._gen_read(node.targets)
        elif isinstance(node, ReadStatement):
            self._gen_read(node.targets)
        else:
            raise CodeGenError(f"Unknown statement node: {type(node).__name__}")

    def _gen_assignment(self, node: Assignment) -> None:
        self._emit(f'    ; {node.target.name} := ...')
        self._gen_expr(node.value)                        # result in rax
        self._ins('mov', self._var_addr(node.target.decl), 'rax')

    def _gen_if(self, node: IfStatement) -> None:
        else_lbl = self._new_label()
        end_lbl  = self._new_label()

        self._gen_expr(node.condition)
        self._ins('test', 'rax', 'rax')
        self._ins('jz',   else_lbl)

        self._gen_stmt(node.then_branch)
        self._ins('jmp',  end_lbl)

        self._label(else_lbl)
        if node.else_branch:
            self._gen_stmt(node.else_branch)

        self._label(end_lbl)

    def _gen_while(self, node: WhileStatement) -> None:
        start_lbl = self._new_label()
        end_lbl   = self._new_label()

        self._label(start_lbl)
        self._gen_expr(node.condition)
        self._ins('test', 'rax', 'rax')
        self._ins('jz',   end_lbl)

        self._gen_stmt(node.body)
        self._ins('jmp',  start_lbl)

        self._label(end_lbl)

    def _gen_for(self, node: ForStatement) -> None:
        """
        FOR i := start TO stop DO body
        Compiles to:
            i := start
        .start:
            if i > stop  → jmp .end    (or i < stop for DOWNTO)
            body
            i := i ± 1
            jmp .start
        .end:
        """
        start_lbl = self._new_label()
        end_lbl   = self._new_label()
        decl      = node.var.decl
        addr      = self._var_addr(decl)

        # Initialise loop variable
        self._gen_expr(node.start)
        self._ins('mov', addr, 'rax')

        # Evaluate stop value into a callee-saved register (r12)
        self._ins('push', 'r12')
        self._gen_expr(node.stop)
        self._ins('mov',  'r12', 'rax')

        self._label(start_lbl)
        self._ins('mov', 'rax', addr)
        self._ins('cmp', 'rax', 'r12')
        if node.downto:
            self._ins('jl', end_lbl)   # i < stop → done
        else:
            self._ins('jg', end_lbl)   # i > stop → done

        self._gen_stmt(node.body)

        # Increment / decrement
        self._ins('mov', 'rax', addr)
        if node.downto:
            self._ins('dec', 'rax')
        else:
            self._ins('inc', 'rax')
        self._ins('mov', addr, 'rax')
        self._ins('jmp', start_lbl)

        self._label(end_lbl)
        self._ins('pop', 'r12')

    # ── I/O ──────────────────────────────────────────────────

    def _call_printf(self, fmt_label: str, *extra_regs: tuple[str, str]) -> None:
        """
        Emit a printf call.
        fmt_label  : label of the format string in .data
        extra_regs : list of (reg, value) movs to set up before call
                     The format address is always loaded into rdi.
        """
        self._ins('lea',  'rdi', f'[rel {fmt_label}]')
        for reg, val in extra_regs:
            if val != reg:                            # skip no-op moves
                self._ins('mov', reg, val)
        self._ins('xor',  'eax', 'eax')              # AL=0 → no XMM args
        self._ins('call', 'printf WRT ..plt')

    def _gen_write(self, args: tuple, newline: bool) -> None:
        for arg in args:
            vtype = getattr(arg, 'var_type', PascalType.UNKNOWN)
            self._gen_expr(arg)   # result in rax

            if vtype == PascalType.INTEGER:
                fmt = '_fmt_intln' if newline else '_fmt_int'
                self._call_printf(fmt, ('rsi', 'rax'))

            elif vtype == PascalType.BOOLEAN:
                # Boolean: print TRUE or FALSE string
                fmt = '_fmt_booln' if newline else '_fmt_bool'
                skip_lbl = self._new_label()
                end_lbl  = self._new_label()
                self._ins('test', 'rax', 'rax')
                self._ins('jnz',  skip_lbl)
                self._ins('lea',  'rsi', '[rel _str_false]')
                self._ins('jmp',  end_lbl)
                self._label(skip_lbl)
                self._ins('lea',  'rsi', '[rel _str_true]')
                self._label(end_lbl)
                self._call_printf(fmt)

            elif vtype == PascalType.CHAR:
                fmt = '_fmt_charln' if newline else '_fmt_char'
                self._call_printf(fmt, ('rsi', 'rax'))

            elif vtype == PascalType.STRING:
                fmt = '_fmt_strln' if newline else '_fmt_str'
                # rax already holds address of the string literal
                self._call_printf(fmt, ('rsi', 'rax'))

            else:
                # Fallback: treat as integer
                fmt = '_fmt_intln' if newline else '_fmt_int'
                self._call_printf(fmt, ('rsi', 'rax'))

        # writeln with no args → just print newline
        if not args and newline:
            self._ins('xor',  'edi', 'edi')
            self._ins('mov',  'dil', '10')    # '\n'
            self._ins('call', 'putchar WRT ..plt')

    def _gen_read(self, targets: tuple) -> None:
        for ref in targets:
            decl  = ref.decl
            vtype = decl.var_type
            addr  = self._var_addr(decl)

            if vtype in (PascalType.INTEGER, PascalType.BOOLEAN):
                self._ins('lea',  'rdi', '[rel _fmt_rdi]')
                self._ins('lea',  'rsi', addr)
                self._ins('xor',  'eax', 'eax')
                self._ins('call', 'scanf WRT ..plt')

            elif vtype == PascalType.CHAR:
                # Read a single char via scanf " %c" (leading space skips whitespace)
                self._ins('lea',  'rdi', '[rel _fmt_rdc]')
                self._ins('lea',  'rsi', addr)
                self._ins('xor',  'eax', 'eax')
                self._ins('call', 'scanf WRT ..plt')

    # ══════════════════════════════════════════════════════════
    #  Expression generators  (result always in rax)
    # ══════════════════════════════════════════════════════════

    def _gen_expr(self, node: ASTNode) -> None:
        """Evaluate expression; leave result in rax."""

        if isinstance(node, IntLiteral):
            self._ins('mov', 'rax', str(node.value))

        elif isinstance(node, BoolLiteral):
            self._ins('mov', 'rax', '1' if node.value else '0')

        elif isinstance(node, CharLiteral):
            self._ins('mov', 'rax', str(ord(node.value)))

        elif isinstance(node, StringLiteral):
            lbl = self._new_str_label(node.value)
            self._ins('lea', 'rax', f'[rel {lbl}]')

        elif isinstance(node, VarRef):
            self._ins('mov', 'rax', self._var_addr(node.decl))

        elif isinstance(node, UnaryOp):
            self._gen_unary(node)

        elif isinstance(node, BinaryOp):
            self._gen_binary(node)

        else:
            raise CodeGenError(f"Unknown expr node: {type(node).__name__}")

    def _gen_unary(self, node: UnaryOp) -> None:
        self._gen_expr(node.operand)
        if node.op == UnOp.NEG:
            self._ins('neg', 'rax')
        elif node.op == UnOp.NOT:
            # Boolean NOT: xor with 1  (0→1, 1→0)
            self._ins('xor', 'rax', '1')

    def _gen_binary(self, node: BinaryOp) -> None:
        op = node.op

        # Short-circuit evaluation for 'and' / 'or'
        if op == BinOp.AND:
            self._gen_short_circuit_and(node)
            return
        if op == BinOp.OR:
            self._gen_short_circuit_or(node)
            return

        # General case: eval left → push, eval right, combine
        self._gen_expr(node.left)
        self._ins('push', 'rax')
        self._gen_expr(node.right)
        self._ins('mov',  'rcx', 'rax')   # right operand in rcx
        self._ins('pop',  'rax')           # left  operand in rax

        if op == BinOp.ADD:
            self._ins('add', 'rax', 'rcx')

        elif op == BinOp.SUB:
            self._ins('sub', 'rax', 'rcx')

        elif op == BinOp.MUL:
            self._ins('imul', 'rax', 'rcx')

        elif op == BinOp.DIV:
            # idiv requires rdx:rax; sign-extend rax into rdx
            self._ins('cqo')
            self._ins('idiv', 'rcx')
            # rax = quotient

        elif op == BinOp.MOD:
            self._ins('cqo')
            self._ins('idiv', 'rcx')
            self._ins('mov',  'rax', 'rdx')   # rdx = remainder

        else:
            # Relational operators → result is 0 or 1 in rax
            self._gen_relational(op)

    def _gen_relational(self, op: BinOp) -> None:
        """
        After  cmp rax, rcx  is done by the caller, emit a conditional SET.
        rax = left, rcx = right already loaded.
        """
        self._ins('cmp', 'rax', 'rcx')
        jmp_map = {
            BinOp.EQ:  'sete',
            BinOp.NEQ: 'setne',
            BinOp.LT:  'setl',
            BinOp.GT:  'setg',
            BinOp.LTE: 'setle',
            BinOp.GTE: 'setge',
        }
        set_ins = jmp_map[op]
        self._ins(set_ins, 'al')
        self._ins('movzx', 'rax', 'al')

    def _gen_short_circuit_and(self, node: BinaryOp) -> None:
        """AND: if left is false, skip right."""
        false_lbl = self._new_label()
        end_lbl   = self._new_label()
        self._gen_expr(node.left)
        self._ins('test', 'rax', 'rax')
        self._ins('jz',   false_lbl)
        self._gen_expr(node.right)
        self._ins('test', 'rax', 'rax')
        self._ins('jz',   false_lbl)
        self._ins('mov',  'rax', '1')
        self._ins('jmp',  end_lbl)
        self._label(false_lbl)
        self._ins('xor',  'eax', 'eax')
        self._label(end_lbl)

    def _gen_short_circuit_or(self, node: BinaryOp) -> None:
        """OR: if left is true, skip right."""
        true_lbl = self._new_label()
        end_lbl  = self._new_label()
        self._gen_expr(node.left)
        self._ins('test', 'rax', 'rax')
        self._ins('jnz',  true_lbl)
        self._gen_expr(node.right)
        self._ins('test', 'rax', 'rax')
        self._ins('jnz',  true_lbl)
        self._ins('xor',  'eax', 'eax')
        self._ins('jmp',  end_lbl)
        self._label(true_lbl)
        self._ins('mov',  'rax', '1')
        self._label(end_lbl)
